### ISSUE TITLE
[Cinnamon] Sound applet position bar breaks panel.

### ISSUE THREAD

**Issue by soonan5** [linuxmint/mint21-beta#20]
How to reproduce:

Start an audio or video track with any media player. Then use the sound applet to change the position of the track. You will notice that **it has not worked**. This will also **break the panel** (you won't be able to open any items in it).
![LM21VCBSA](https://user-images.githubusercontent.com/109312533/179074580-c2602652-83ba-44cd-8c8b-b50a957d407d.jpg)

**Comment by Harry-W-Haines-III** [comment]
I was able to reproduce this.  After you hit Esc to get out of the frozen sound panel you can no longer use the mouse to do anything on the panel (access other applets in the tray, minimize, maximize, open the start menu - the super key works though) so you are pretty much locked out using the mouse on anything the panel lives in.
Was successful using Alt+F2 and 'r' to restart Cinnamon.

**Comment by Acheron17** [comment]
This was fixed in a round of Cinnamon updates.  The hang is no longer present on my system and all aspects of the player from the sound panel are working as expected.
Could you please do an update and check your system?

**Comment by ghost** [comment]
Hi! I have applied all the updates related to Cinnamon 5.4.4 but the problem is still present on my system. Did you apply any updates not related to the Cinnamon desktop? If so this may be the solution to the problem. Thanks!

**Comment by Acheron17** [comment]
I have applied all the updates.
